version: '3.9'

services:
  llm_api:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    # command: gunicorn --worker-class eventlet --workers 1 --bind 0.0.0.0:5000 --timeout 300 app:app
    volumes:
      - ./models:/app/models
    environment:
      - DEBUG_MODE=False